version: '3'

services:
  app:
    build: .
    # image: vdsanku6/dialrx-app:v1.0.0
    container_name: dialrx-app
    command: >
      sh -c "python /app/app.py & 
             streamlit run /app/ui/app.py"
    volumes:
      - ./application:/app
    ports:
      - "8501:8501"
      - "5001:5001"

  qdrant:
    image: qdrant/qdrant
    volumes:
      - ./application/qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
